language: python
python: 2.7.14
sudo: false
cache:
  directories:
  - eggs
  - downloads
env:
  matrix:
    - PLONE_VERSION=5.1
matrix:
  fast_finish: true
install:
  - sed -ie "s#test-5.1.x#test-$PLONE_VERSION.x#" buildout.cfg
  - virtualenv .
  - bin/pip install -U pip
  - bin/pip install -r requirements.txt
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - bin/pip install coveralls
  - bin/coveralls
notifications:
  email:
    - jk@kleinundpartner.at
